#!/bin/bash


dotfiles=(
    gitconfig-gitlab
    gitconfig
    tmux.conf
    zshrc
)

# create links
symlink(){
    printf '%s -> %s\n' "${1}" "${2}"
    ln -nsf "$@"
}


echo -e "\e[32m[➤] Setting up Oh My Zsh plugins...\e[0m"
ZSH_CUSTOM=${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}

declare -A plugins=(
    [zsh-autosuggestions]="https://github.com/zsh-users/zsh-autosuggestions.git"
    [zsh-syntax-highlighting]="https://github.com/zsh-users/zsh-syntax-highlighting.git"
    [fast-syntax-highlighting]="https://github.com/zdharma-continuum/fast-syntax-highlighting.git"
    [zsh-autocomplete]="https://github.com/marlonrichert/zsh-autocomplete.git"
)

for plugin in "${!plugins[@]}"
do 
    dest="$ZSH_CUSTOM/plugins/$plugin"
    if [[ -d "$dest" ]]
    then
        echo "$plugin already installed!"
    else
        sudo git clone --depth 1 "${plugins[$plugin]}" "$dest" # only download the latest commit of the repository’s history.
        echo "$plugin installed successfully!"
    fi
done

echo -e "\e[32m[➤] Installing TMUX Plugin Manager...\e[0m"

if [[ -d "$HOME/.tmux/plugins/tpm" ]]
then
    echo -e "\e[32m[✓] TMUX Plugin Manager already installed!\e[0m"
else
    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
    echo -e "\e[32m[✓] TMUX Plugin Manager installed successfully!\e[0m"
fi


echo -e "\e[32m[➤] Linking Files...\e[0m"
for f in "${dotfiles[@]}"
do  
    # if target file is a dir and not a symlink, create a backup file and delete original file
    [[ -d ~/.$f && ! -L ~/.$f ]] && cp ~/.$f ~/.$f.bak && rm -r ~/.$f
    symlink "$PWD/$f" ~/."$f"

done

echo -e "\e[32m[✓] Setup Completed Successfully!\e[0m"




