#!/usr/bin/env bash



pkgs=(
    git
    curl
    zsh
    tmux
    ncdu
    bat
    htop
)

available(){
    command -v "${1}" > /dev/null;
}


echo -e "\e[32m[➤] Installing packages...\e[0m"

if available apt-get
then
    sudo apt-get -y --ignore-missing install "${pkgs[@]}" 

elif available dnf 
then
    sudo dnf install --skip-unavailable -y "${pkgs[@]}" 
fi

echo -e "\e[32m[✓] Package installation Completed Successfully!\e[0m"

if [[ -d "$HOME/.oh-my-zsh" ]]
then
    echo -e "\e[32m[✓] Oh My Zsh already installed.\e[0m"
else
    echo -e "\e[32m[➤] Installing Oh My Zsh (non-interactive)...\e[0m"
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" --unattended --keep-zshrc
    echo -e "\e[32m[✓] Oh My Zsh installed successfully!\e[0m"
fi




