#!/bin/bash


BIN_DIR="$HOME/.bin"

LOCAL_BIN_DIR="$HOME/.local/bin"

BINARIES=(
    bakup
    weather
    mkvmd
)

BASE_URL="https://gitlab.com/tin3ga/bin/-/raw/main/"

# make a .bin directory and a .local/bin directory to store binaries
mkdir -p "$BIN_DIR"
mkdir -p "$LOCAL_BIN_DIR"

# download binaries save them to .bin directory
echo -e "\e[32m[➤] Downloading binaries...\e[0m"

for binary in "${BINARIES[@]}"
do
    curl -Os "$BASE_URL""$binary" --output-dir "$BIN_DIR"
    chmod +x "$BIN_DIR"/"$binary"
    echo "$binary downloaded successfully!"
done


# download kubectl - saves binary in .local.bin directory

if [[ -a "$LOCAL_BIN_DIR/kubectl" ]]
then
    echo -e "\e[32m[✓] Kubectl Binary already downloaded!\e[0m" 
else
    echo -e "\e[32m[➤] Downloading kubectl binary...\e[0m"
    curl -sLO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" --output-dir "$LOCAL_BIN_DIR"

    chmod +x "$LOCAL_BIN_DIR"/kubectl
    echo -e "\e[32m[✓] Kubectl Binary downloaded successfully!\e[0m"
fi
